name: Copy Content to Release Branches

on:
  push:
    branches:
      - master

jobs:
  copy-uk-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy UK content to uk-docs-release branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -B uk-docs-release
          git rm -rf .
          git checkout master -- uk-docs
          git mv uk-docs/* .
          git commit -m "Update UK docs"
          git push origin uk-docs-release --force

  copy-eu-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy EU content to eu-docs-release branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -B eu-docs-release
          git rm -rf .
          git checkout master -- eu-docs
          git mv eu-docs/* .
          git commit -m "Update EU docs"
          git push origin eu-docs-release --force
